sudo: required
dist: trusty
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - "9"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3
after_success:
  - cat ./coverage/**/*.info | ./node_modules/coveralls/bin/coveralls.js
